// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Hasher is an autogenerated mock type for the Hasher type
type Hasher struct {
	mock.Mock
}

type Hasher_Expecter struct {
	mock *mock.Mock
}

func (_m *Hasher) EXPECT() *Hasher_Expecter {
	return &Hasher_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function with given fields: plaintextPassword
func (_m *Hasher) Hash(plaintextPassword string) (string, error) {
	ret := _m.Called(plaintextPassword)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(plaintextPassword)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(plaintextPassword)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(plaintextPassword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Hasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type Hasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - plaintextPassword string
func (_e *Hasher_Expecter) Hash(plaintextPassword interface{}) *Hasher_Hash_Call {
	return &Hasher_Hash_Call{Call: _e.mock.On("Hash", plaintextPassword)}
}

func (_c *Hasher_Hash_Call) Run(run func(plaintextPassword string)) *Hasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Hasher_Hash_Call) Return(_a0 string, _a1 error) *Hasher_Hash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Hasher_Hash_Call) RunAndReturn(run func(string) (string, error)) *Hasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// Matches provides a mock function with given fields: plaintextPassword, hashedPassword
func (_m *Hasher) Matches(plaintextPassword string, hashedPassword string) (bool, error) {
	ret := _m.Called(plaintextPassword, hashedPassword)

	if len(ret) == 0 {
		panic("no return value specified for Matches")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(plaintextPassword, hashedPassword)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(plaintextPassword, hashedPassword)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(plaintextPassword, hashedPassword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Hasher_Matches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Matches'
type Hasher_Matches_Call struct {
	*mock.Call
}

// Matches is a helper method to define mock.On call
//   - plaintextPassword string
//   - hashedPassword string
func (_e *Hasher_Expecter) Matches(plaintextPassword interface{}, hashedPassword interface{}) *Hasher_Matches_Call {
	return &Hasher_Matches_Call{Call: _e.mock.On("Matches", plaintextPassword, hashedPassword)}
}

func (_c *Hasher_Matches_Call) Run(run func(plaintextPassword string, hashedPassword string)) *Hasher_Matches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Hasher_Matches_Call) Return(_a0 bool, _a1 error) *Hasher_Matches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Hasher_Matches_Call) RunAndReturn(run func(string, string) (bool, error)) *Hasher_Matches_Call {
	_c.Call.Return(run)
	return _c
}

// NewHasher creates a new instance of Hasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Hasher {
	mock := &Hasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
