// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForAddRolesForUser implements pgx.CopyFromSource.
type iteratorForAddRolesForUser struct {
	rows                 []AddRolesForUserParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddRolesForUser) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddRolesForUser) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].RoleID,
		r.rows[0].Grantor,
	}, nil
}

func (r iteratorForAddRolesForUser) Err() error {
	return nil
}

func (q *Queries) AddRolesForUser(ctx context.Context, arg []AddRolesForUserParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"users_roles"}, []string{"user_id", "role_id", "grantor"}, &iteratorForAddRolesForUser{rows: arg})
}
