// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: credentials.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createCredentials = `-- name: CreateCredentials :exec
INSERT INTO "credentials"
  ("user_id", "email", "hashed_password")
VALUES
  ($1, $2, $3)
`

type CreateCredentialsParams struct {
	UserID         uuid.UUID `json:"user_id"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
}

func (q *Queries) CreateCredentials(ctx context.Context, arg CreateCredentialsParams) error {
	_, err := q.db.Exec(ctx, createCredentials, arg.UserID, arg.Email, arg.HashedPassword)
	return err
}
