// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Permission struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
	Description string    `json:"description"`
}

type Role struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
	Description string    `json:"description"`
}

type RolesPermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type User struct {
	ID             uuid.UUID   `json:"id"`
	Name           string      `json:"name"`
	Email          string      `json:"email"`
	HashedPassword pgtype.Text `json:"hashed_password"`
	Status         string      `json:"status"`
}

type UsersRole struct {
	UserID    uuid.UUID        `json:"user_id"`
	RoleID    uuid.UUID        `json:"role_id"`
	Grantor   uuid.UUID        `json:"grantor"`
	GrantedAt pgtype.Timestamp `json:"granted_at"`
}
