// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Absence struct {
	ID        uuid.UUID        `json:"id"`
	Employee  uuid.UUID        `json:"employee"`
	Reason    string           `json:"reason"`
	FromDate  pgtype.Date      `json:"from_date"`
	ToDate    pgtype.Date      `json:"to_date"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type AttendanceRecord struct {
	ID        uuid.UUID        `json:"id"`
	Employee  uuid.UUID        `json:"employee"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Employee struct {
	ID             uuid.UUID   `json:"id"`
	Name           string      `json:"name"`
	Email          string      `json:"email"`
	HashedPassword pgtype.Text `json:"hashed_password"`
	Status         string      `json:"status"`
}

type EmployeesRole struct {
	EmployeeID uuid.UUID        `json:"employee_id"`
	RoleID     uuid.UUID        `json:"role_id"`
	Grantor    uuid.UUID        `json:"grantor"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Role struct {
	ID   uuid.UUID `json:"id"`
	Code string    `json:"code"`
}

type Ticket struct {
	ID        uuid.UUID        `json:"id"`
	Requester uuid.UUID        `json:"requester"`
	Attendant uuid.NullUUID    `json:"attendant"`
	Status    string           `json:"status"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
