// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddRolesForUser(ctx context.Context, arg []AddRolesForUserParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error)
	GetRolesByCodes(ctx context.Context, codes []string) ([]uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
