// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddRolesForEmployee(ctx context.Context, arg []AddRolesForEmployeeParams) (int64, error)
	CheckEmployeeEmailExists(ctx context.Context, email string) (bool, error)
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (CreateEmployeeRow, error)
	CreateRoles(ctx context.Context, code []string) (int64, error)
	GetEmployeeByEmail(ctx context.Context, email string) (Employee, error)
	GetEmployeeByID(ctx context.Context, id uuid.UUID) (Employee, error)
	GetRoles(ctx context.Context) ([]Role, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) error
}

var _ Querier = (*Queries)(nil)
